### ISSUE TITLE
Transaction interface cannot be used

### ISSUE THREAD

**Issue by yinprint** [hbdmapi/huobi_usdt_swap_Java#3]
{"status":"error","err_code":1030,"err_msg":"Abnormal service. Please try again later.","ts":1621378117939}

**Comment by yinprint** [comment]
All method calls return this in TradeAPITest

**Comment by fuwei6056** [comment]
Q1: What is the reason for 1030 error code?
If you encounter errors such as {"status":"error","err_code":1030,"err_msg":"Abnormal service. Please try again later.","ts":1588093883199},indicating that your input request parameter is not correct, please print your request body and complete URL parameters, and please check the corresponding API document interface one by one.The common example is that the volume must be an integer.

**Comment by fuwei6056** [comment]
what api interface is which reported that error? we will check it

**Comment by yinprint** [comment]
thinks ，I was wrong
