### ISSUE TITLE
我的币在usdt全仓里面,我用github 提供的方法 提示1047 但是手动可以下单成功

### ISSUE THREAD

**Issue by TokenScience01** [hbdmapi/huobi_usdt_swap_Java#5]
测试类是com.huobi.linear.swap.api.TradeAPITest类的swapOrderRequest()方法
//填写申请的API-KEY 和 SECRET   
HuobiAPIServiceImpl huobiAPIService = new HuobiAPIServiceImpl("API-KEY", "SECRET");
@Test
public void swapOrderRequest() {
    SwapOrderRequest request = SwapOrderRequest.builder()
            .contractCode("BTC-USDT")
            .volume(100l)
            .price(BigDecimal.valueOf(10121))
            .direction(DirectionEnum.SELL)
            .offset(OffsetEnum.OPEN)
            .leverRate(5)
            .orderPriceType("opponent")
            .build();
    SwapOrderResponse response =
            huobiAPIService.swapOrderRequest(request);
    logger.debug("1合约下单：{}", JSON.toJSONString(response));
}

用这个方法 提示 {"status":"error","err_code":1047,"err_msg":"Insufficient margin available.","ts":1622033531177}

**Comment by fuwei6056** [comment]
关于1047可用保证金不足的检查方法：
使用XXX_account_info(获取用户账户信息)的接口来确定。
    a、通过margin_balance（账户权益）字段来确定你账户上的金额是否充足。
    b、通过margin_balance（账户权益）的金额数据来确认你现在所使用的API KEY 和 WEB或APP上的账户是否对应。
    c、通过margin_available（可用保证金）字段来确定你是否还有余额来进行开仓。
    d、当可以保证金比较少时，且使用的是"limit":限价，"post_only":只做maker单，ioc:IOC订单，fok：FOK订单 这四种报价方式时。你需要确认price（价格）是否设置的太高。
如果你对上面的确认方法有疑问可以咨询在线客服来帮你解答。

**Comment by fuwei6056** [comment]
你使用的是逐仓合约的接口。要使用全逐全约接口swapCrossOrderRequest() 这个方法。
