### ISSUE TITLE
How to connect TPSL order with an existing opened long position

### ISSUE THREAD

**Issue by alexander-myltsev** [hbdmapi/huobi_usdt_swap_Java#7]
I use `huobiCrossAPIService.swapCrossOrderRequest` to place the order. It produces the Request:

```
Request{
  method=POST, 
  url=https://api.hbdm.com/linear-swap-api/v1/swap_cross_order?
    volume=1&
    lever_rate=10&
    SignatureVersion=2&
    offset=open&
    contract_code=BTC-USDT&
    AccessKeyId=h6n2***&
    Signature=yHZS***&
    SignatureMethod=HmacSHA256&
    order_price_type=opponent&
    Timestamp=2021-10-18T11%3A38%3A06&
    direction=buy, 
  tag=null}
```

in response I get:

```
SwapCrossOrderResponse(status=ok, data=SwapCrossOrderResponse.DataBean(orderId=89***76, orderIdStr=89***76, clientOrderId=null), ts=1634557188608)
```

--- 

Then I need to place TPSL order. I naively tried to fill request parameters as follows:

```
val request = SwapTpslOrderRequest.builder()
  .contractCode(contractCode) // BTC-USDT
  .volume(volume.bigDecimal) // 1
 .slTriggerPrice(sellPrice) // currentPrice - 5.0
  .direction(DirectionEnum.SELL.getValue)
 .build()
```

which produces the Request:

```
Request{
  method=POST, 
  url=https://api.hbdm.com/linear-swap-api/v1/swap_cross_tpsl_order?
    volume=1&
    SignatureVersion=2&
    contract_code=BTC-USDT&
    AccessKeyId=h6n2***&
    sl_trigger_price=61251.2&
    Signature=rd7f***&
    SignatureMethod=HmacSHA256&
    Timestamp=2021-10-18T11%3A44%3A00&
    direction=sell, 
  tag=null}
```

and get the response:

```
{"status":"error","err_code":1069,"err_msg":"The price is not reasonable.","ts":1634557478538}
```

---

I use ceiling to tenths:

```
val sellPrice = (currentPrice - 5).setScale(1, RoundingMode.CEILING).bigDecimal
// currentPrice is the price of the contract from /linear-swap-notification
```

which fits the `price_tick` of BTC_USDT. I don't know the reason of “price is not reasonable”.

---

Please, explain how to connect TPSL order with an existing opened long position?

**Comment by fuwei6056** [comment]
Your problem should be that this place (.sltriggerPrice (sellPrice) // currentPrice-5.0) evaluates to something other than a decimal place. You can print out the result in the program.

**Comment by alexander-myltsev** [comment]
> Your problem should be that this place (.sltriggerPrice (sellPrice) // currentPrice-5.0) evaluates to something other than a decimal place. You can print out the result in the program.

As I said, I compute it as follows:

```
val sellPrice = (currentPrice - 5).setScale(1, RoundingMode.CEILING).bigDecimal
```

I'm pretty sure it doesn't go out of the required precision.

**Comment by fuwei6056** [comment]
When you use [swap_cross_tpsl_order] this interface, there are two situations:
1、the sl_order_price_type is limite：sl_trigger_price、sl_order_price and sl_order_price_type these three parameters need to be uploaded at the same time.
2、the sl_order_price_type is optimal_5，optimal_10，optimal_20：sl_order_price can be omitted
So， your problem is you didn't upload sl_order_price

**Comment by alexander-myltsev** [comment]
Thanks. That worked out.
